name: pyhsmm-autoregressive

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.8
    - conda-forge::h5py=3.6.0
    - conda-forge::numpy=1.21.2
    - conda-forge::cython
    - future
    - conda-forge::eigen
    - requests
    - pip
    - pip:
        # - future
        - "--editable=./"